{
  admin_name : ${{ secrets.SECRET_admin_name }},
  admin_pass : ${{ secrets.SECRET_admin_pass }},
  db_username : ${{ secrets.SECRET_username }},
  db_pass : ${{ secrets.SECRET_pass }},
  db_host : ${{ secrets.SECRET_host }}
}
