admin_name : 'Menvar4077'
admin_pass : 'wTa/mt75Of69'
db_username : 'jefrslcddkhkfy'
db_pass : "fc0e3b12ea31dc3fbe7c962efe5f16c60eebd068e787208701e5c1ee41c9a16c"
db_host : 'ec2-3-225-110-188.compute-1.amazonaws.com'
db_port : '5432'
db_name : 'd2me4f3spi75cv'